title: "Sidney Airport Club"

plugins:
  - jekyll-inline-svg

collections:
  meetings:
    output: true
    permalink: /meetings/:path/

future: true

defaults:
  - scope:
      path: ""
      type: "meetings"
    values:
      layout: "meeting"

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
  - assets/css/tailwind-input.css
